### ISSUE TITLE
net-framework-4-7-2-referencing-net-standard-2-0-project

### ISSUE THREAD

**Issue by BenKoth** [microsoft/sqlmanagementobjects#10]
My situation: I have a .Net 4.7.2 WinForms application. It references a project that is a .Net Standard class library The .Net Standard library references the Microsoft.SqlServer.SqlManagementObjects NuGet package using a PackageReference

When I build the winforms application, it is pulling in the Microsoft.SqlServer.SqlManagementObjects package from the net462 lib folder instead of the netstandard2.0 folder. This is a problem because the .Net Standard version of the library has different classes (e.g. it uses Microsoft.Data.SqlConnection instead of System.Data.SqlConnection). So when the application is run you get an error saying System.MissingMethodException: Method not found: 'Void Microsoft.SqlServer.Management.Common.ServerConnection..ctor(Microsoft.Data.SqlClient.SqlConnection)'

Is there any way around this? I feel like the SMO libraries should have been separated into different packages for .Net Standard and .Net Framework if they have differences like this.

**Comment by shueybubbles** [comment]
Hi @BenKoth , thanx for the report. We're still figuring out the nuances of the new packagereference-based world. Most of our internal projects still use packages.config and have explicit dependency management. 
Eventually SMO will lose this dichotomy and both netfx and netstandard (or netcore3 maybe?) bits will use Microsoft.Data.SqlClient.

The only workaround I can think of right now is kinda messy, which is to mark your dependency packagereference with privateAssets=all and to manually copy around all the right SMO DLLs as part of your build. 
If you add your own PackageReference to Microsoft.Data.SqlClient you'll get the net46 version of that.

**Comment by shueybubbles** [comment]
How might this proposal be accepted by the SMO developer community? 
1. We create a second SMO package called "Microsoft.SqlServer.SqlManagementObjects.SSMS". This package would contain netfx-only binaries, version 16.100, using System.Data.SqlClient. These binaries would align with what ships in SSMS (and likely SSDT). SSMS 18.x extension developers would use this package.

2. At the same time, we rev Microsoft.SqlServer.SqlManagementObjects to use Microsoft.Data.SqlClient 1.1.3 in both netfx and netstandard binaries. Those binaries will have version 16.200.

3. Once SSMS is ready to switch to Microsoft.Data.SqlClient, we stop revving the SSMS-specific SMO package.

**Comment by shueybubbles** [comment]
@BenKoth try version 161.40241.8-msdata
