### ISSUE TITLE
SqlManagementObjects version 161.xxx fails to connect to any database

### ISSUE THREAD

**Issue by jkiller295** [microsoft/sqlmanagementobjects#111]
There is an issue with Microsoft.SqlServer.SqlManagementObjects version 161.xxx onwards.

SQL server version 15.0.4236

I'm using the following code to connect to a database on my local SQL server
```csharp
          Server sqlServer = new Server("ADMIN\\SQLEXPRESS")
          {
                ConnectionContext =
                {
                    LoginSecure = true
                }
           };
           Database sqlDb = new Database(sqlServer, "Test DB"); //fails at this line
```
Error message is:
> Microsoft.SqlServer.Management.Smo.FailedOperationException: 'SetParent failed for Database 'Test DB'.' 

Inner message:
> SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: HTTP Provider, error: 0 - )

However, when I downgrade to version 160.xxx, the problem goes away. I tested every minor releases of version 161.xxx and all of them had the same problem. Any idea about this?

**Comment by shueybubbles** [comment]
does it work if you construct a `ServerConnection` instance first and pass it to the `Server` constructor?

**Comment by shueybubbles** [comment]
oh - and if you are trying to get an existing Database, can you use `sqlServer.Databases["Test DB"]` ?

**Comment by shueybubbles** [comment]
I wonder why the provider is `HTTP Provider`.

**Comment by shueybubbles** [comment]
I think you could try writing a simple Microsoft.Data.SqlClient -based app that creates a `SqlConnection` object pointing to your server and see if it can run a query. That would isolate the issue to either SMO or to SqlClient.

**Comment by jkiller295** [comment]
> **does it work if you construct a `ServerConnection` instance first and pass it to the `Server` constructor?**

This code throws the same `FailedOperationException` as the previous one
```csharp
          using (SqlConnection sqlCon = new SqlConnection("Server=ADMIN\\SQLEXPRESS;Database=Test DB;Trusted_Connection=True;"))
          {
              sqlCon.Open();
              ServerConnection serverCon = new ServerConnection(sqlCon);
              Server sqlServer = new Server(serverCon);
              Database sqlDb = new Database(sqlServer, "Test DB");
              sqlDb.Tables.Refresh();
              foreach (Table tbl in sqlDb.Tables)
              {
                  Console.WriteLine(tbl.Name);
              }
          }
```
> **oh - and if you are trying to get an existing Database, can you use `sqlServer.Databases["Test DB"]` ?**

Doing this throws `ConnectionFailureException: 'Failed to connect to server JACK\SQLEXPRESS.'`
but with the same inner message:
> SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: HTTP Provider, error: 0 - )

```csharp
          using (SqlConnection sqlCon = new SqlConnection("Server=ADMIN\\SQLEXPRESS;Database=Test DB;Trusted_Connection=True;"))
          {
              sqlCon.Open();
              ServerConnection serverCon = new ServerConnection(sqlCon);
              Server sqlServer = new Server(serverCon);
              Database sqlDb = sqlServer.Databases["Test DB"];
              sqlDb.Tables.Refresh();
              foreach (Table tbl in sqlDb.Tables)
              {
                  Console.WriteLine(tbl.Name);
              }
          }
```

**Comment by jkiller295** [comment]
> I think you could try writing a simple Microsoft.Data.SqlClient -based app that creates a `SqlConnection` object pointing to your server and see if it can run a query. That would isolate the issue to either SMO or to SqlClient.

I think I'm getting somewhere

`Microsoft.Data.SqlClient;` fails to open a connection whereas `System.Data.SqlClient` succeeds with the following code

```csharp
using (SqlConnection sqlCon = new SqlConnection("Server=JACK\\SQLEXPRESS;Database=PRM;Trusted_Connection=True;"))
{
        sqlCon.Open();
}
```

**Comment by jkiller295** [comment]
For a piece that is as simple as this also fails with version 161.xxx but succeeds in 160.xxx and earlier
```csharp
ServerConnection srvConn = new ServerConnection
{
      ServerInstance = @".\" + "SQLEXPRESS",
      LoginSecure = true 
};
Server srv = new Server(srvConn);
Console.WriteLine(srv.Information.Version);
```
Exception thrown:
> ConnectionFailureException: 'Failed to connect to server .\SQLEXPRESS.'

Inner message:
> SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: HTTP Provider, error: 0 - )

**Comment by shueybubbles** [comment]
Pls open an issue on github.com/dotnet/sqlclient
Having the full call stack where the exception is thrown will help them too. 

One issue to be aware of is if you are using Microsoft.Data.SqlClient 4.1 or newer, it defaults to `Encrypt=true`. The error you see doesn't indicate that is the problem to me, though.

**Comment by jkiller295** [comment]
> Pls open an issue on github.com/dotnet/sqlclient Having the full call stack where the exception is thrown will help them too.
> 
> One issue to be aware of is if you are using Microsoft.Data.SqlClient 4.1 or newer, it defaults to `Encrypt=true`. The error you see doesn't indicate that is the problem to me, though.

Please pardon my ignorance, but does the `Server` class call `SqlClient` somewhere internally? I'm not sure if this is the `SqlClient` problem because the version I'm using is 4.1, despite changing the SMO version, `SqlClient` remains unchanged. Also when I checked the connection string created by the `Server` class, it showed `Encrypt=false`.

**Comment by shueybubbles** [comment]
yes the `Server` class uses `Microsoft.Data.SqlClient.SqlConnection` internally. If `SqlConnection.Open` is giving you that error then something is wrong there.

**Comment by jkiller295** [comment]
> yes the `Server` class uses `Microsoft.Data.SqlClient.SqlConnection` internally. If `SqlConnection.Open` is giving you that error then something is wrong there.

But what is the difference between version 161.xx and 160.xx that would cause this problem? How do they call `Microsoft.Data.SqlClient.SqlConnection` (even though the version is 4.1.0 in both cases)?

**Comment by shueybubbles** [comment]
160.x uses `System.Data.SqlClient.SqlConnection` for net462. What `TargetFramework` are you using?

**Comment by jkiller295** [comment]
> 160.x uses `System.Data.SqlClient.SqlConnection` for net462. What `TargetFramework` are you using?

Framework 4.7

**Comment by jkiller295** [comment]
Something strange just happened today. Not sure which dependency package was updated but after updating all of them to the latest version, the initial problem just goes away. 

I'm now using SMO 161.47027.0, SqlClient 5.0.0 and couldn't re-produce the error.

**Comment by jkiller295** [comment]
> For a piece that is as simple as this also fails with version 161.xxx but succeeds in 160.xxx and earlier
> 
> ```cs
> ServerConnection srvConn = new ServerConnection
> {
>       ServerInstance = @".\" + "SQLEXPRESS",
>       LoginSecure = true 
> };
> Server srv = new Server(srvConn);
> Console.WriteLine(srv.Information.Version);
> ```
> 
> Exception thrown:
> 
> > ConnectionFailureException: 'Failed to connect to server .\SQLEXPRESS.'
> 
> Inner message:
> 
> > SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: HTTP Provider, error: 0 - )

I updated all packages to the latest version today, including the `Microsoft.Data.SqlClient` to version 5.0.0 and a new `MissingMethodException` is thrown when running this piece of code.
Message:
> Method not found: 'Void Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_Encrypt(Boolean)'.

Trace:
>    at Microsoft.SqlServer.Management.Common.ConnectionSettings.GetConnectionString()
   at Microsoft.SqlServer.Management.Common.ConnectionSettings.get_ConnectionString()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InitSqlConnectionObject(Boolean setConnectionString, Boolean removeIntegratedSecurity)
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor(IRenewableToken token, Boolean removeIntegratedSecurity)
   at Microsoft.SqlServer.Management.Common.ServerConnection..ctor()
   at TestSqlClient.TestSqlClient.Main() in D:\source\repos\Test code\ConsoleApp1\Program.cs:line 15

**Comment by jkiller295** [comment]
@shueybubbles Looks like the problem comes from the wrong SNI and MDS versions ([SqlClient issue](https://github.com/dotnet/SqlClient/issues/1779)). Should the latest SMO install the correct SNI and MDS versions as dependencies to at least receive the correct error message about SSL encryption instead of the above `HTTP provider`?

**Comment by shueybubbles** [comment]
SMO doesn't install anything, whatever you use to build your app does. The nuget package references a particular version of Microsoft.Data.SqlClient and expects the package manager to resolve dependencies correctly.

**Comment by jkiller295** [comment]
> SMO doesn't install anything, whatever you use to build your app does. The nuget package references a particular version of Microsoft.Data.SqlClient and expects the package manager to resolve dependencies correctly.

Ok, I know from now on I will use the [**Highest** dependency option](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#install-options) to install the latest versions. Problem solved. Thanks @shueybubbles
