### ISSUE TITLE
UnknownPropertyException HasSystemTimePeriod: unknown property.

### ISSUE THREAD

**Issue by jvmlet** [microsoft/sqlmanagementobjects#123]
I'm getting `Microsoft.SqlServer.Management.Smo.UnknownPropertyException
HasSystemTimePeriod: unknown property` when trying to  alter table using 
```c#
        Server server = new Server(new ServerConnection()                {
                    TrustServerCertificate = true,
                    ConnectionString = "....."
               }
            );
       string dbName = new SqlConnectionStringBuilder(server.ConnectionContext.ConnectionString).InitialCatalog;
        Database database = server.Databases[dbName];

        Table smoTestTable = new Table(database, "mytest_table");

        Column column1 = new Column(smoTestTable, "column1", DataType.VarChar(40));
        Column column2 = new Column(smoTestTable, "column2", DataType.VarChar(40));

        smoTestTable.Columns.Add(column1);
        smoTestTable.Columns.Add(column2);
        smoTestTable.Create();             // the table is successfully created
            
        smoTestTable.Columns["column2"].MarkForDrop(true);
        smoTestTable.Alter(); // exception is thrown
```

The DB server is Synapse and `<PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="170.8.0" />`

**Comment by jvmlet** [comment]
Same error with version `170.11.0`

**Comment by shueybubbles** [comment]
`170.12.0` and `161.48036.0` should both have this fix. Please try it out.

**Comment by jvmlet** [comment]
Thanks @shueybubbles , but I'm still getting the same error  with `170.12.0` 
`161.48036.0` works though, my app's `TargetFramework`  is `net6.0`, please reopen the issue

**Comment by shueybubbles** [comment]
Apologies! we had some internal branching issues. Please try with `170.13.0`

**Comment by jvmlet** [comment]
Thanks @shueybubbles , works as expected with `170.13.0`
