### ISSUE TITLE
SMO Table.EnumScript truncates long query

### ISSUE THREAD

**Issue by Bykiev** [microsoft/sqlmanagementobjects#131]
I'm generating INSERT script with SMO, but long queries are truncated for some reason. Please, fix this bug.

**Comment by shueybubbles** [comment]
Can you provide a snippet of code to reproduce the issue?

**Comment by Bykiev** [comment]
Sorry, the issue was not in SMO, but in Visual Studio, which truncates long text in Quick Watch window for some reason
