### ISSUE TITLE
ConnectionHelpers.UpdateConnectionInfoIfCloud creates a new connection when not needed

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/sqlmanagementobjects#143]
If the application creates a `ServerConnection` without using a `SqlConnection` whose initial catalog is a user database in Azure SQL Database, using that ServerConnection as the basis for a SMO `Server` eventually leads to SMO creating a new connection to fetch data from the server because it doesn't match the database name in the URN to the name in `ServerConnection.DatabaseName`:

This is the code to reproduce the issue:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using Microsoft.SqlServer.Management.Common;
using Microsoft.SqlServer.Management.Smo;
using MyClassLibrary;

namespace SmoExampleFramework
{
    internal class Program
    {
        static readonly string ServerName = "<servername>.database.windows.net,1433";
        static readonly string DatabaseName = "<databasename>";

        static void Main(string[] args)
        {
            SmoConnection();
        }

        static void SmoConnection()
        {
            try
            {
                var connectionString = new SqlConnectionStringBuilder
                {
                    DataSource = ServerName,
                    InitialCatalog = DatabaseName,
                    Authentication = SqlAuthenticationMethod.ActiveDirectoryDefault,
                    TrustServerCertificate = true,
                    IntegratedSecurity = false,
                    Encrypt = true,
                    ConnectTimeout = 30,
                    Pooling = false,
                    UserID = "myuser@mydomain.com",
                };
                

                // Get server

 

               // Creating the connection by setting the ConnectionString property is the key to the repro
                var serverConnection = new ServerConnection();
                serverConnection.NonPooledConnection = true;
                serverConnection.ConnectionString = connectionString.ToString();
                var server = new Server(serverConnection);

                // Add table and column to database
                var database = server.Databases[DatabaseName];
                var databaseDefinition = new DatabaseDefinition(database);
                var smoTable = databaseDefinition.GetSmoTable("newtable");
                smoTable.Entity.Columns.Add(smoTable.Entity.CreateDataColumn("newcolumn"));
                databaseDefinition.SaveChanges();

                // disconnect
                server.ConnectionContext.Connect();
                Console.WriteLine(server.Information.Version);
                server.ConnectionContext.Disconnect();

                Console.WriteLine("Disconnected");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            Console.WriteLine("Press any key to disconnect");
            Console.ReadLine();
        }
    }
}
```

There are two ways to work around this problem:
1. set `serverConnection.DatabaseName = DatabaseName;` in addition to setting the `ConnectionString`  property, or
2. Create the ServerConnection from a SqlConnection:
```C#
                var serverConnection = new ServerConnection(new SqlConnection(connectionString.ConnectionString));
//                serverConnection.NonPooledConnection = true;
 //               serverConnection.ConnectionString = connectionString.ToString();
                var server = new Server(serverConnection);
```

**Comment by MalcolmMcNeely** [comment]
More context for the sample code:
```
public class DatabaseDefinition
    {
        readonly Database _database;
        readonly IDictionary<string, DatabaseChange<Table>> _tableChanges = new Dictionary<string, DatabaseChange<Table>>();

        public DatabaseDefinition(Database database)
        {
            _database = database;
        }

        public DatabaseChange<Table> GetSmoTable(string tableName)
        {
            if (_tableChanges.TryGetValue(tableName, out var dbChange))
            {
                return dbChange;
            }

            var table = _database.Tables[tableName] ?? new Table(_database, tableName);

            dbChange = new DatabaseChange<Table>(table);

            _tableChanges.Add(tableName, dbChange);

            return dbChange;
        }

        public void SaveChanges()
        {
            foreach (var databaseChange in _tableChanges.Values)
            {
                databaseChange.Save();
            }
            _tableChanges.Clear();
        }
    }
```
```
public class DatabaseChange<T> where T : SmoObjectBase, ICreatable, IAlterable
    {
        public DatabaseChange(T entity)
        {
            Entity = entity;
        }

        public T Entity { get; }

        public void Save()
        {
            if (Entity.State == SqlSmoState.Creating)
            {
                Entity.Create();
            }
            else
            {
                Entity.Alter();
            }
        }
    }
```
```
        public static Column CreateDataColumn(this Table smoTable, string name)
        {
            return new Column(smoTable, name, DataType.NVarChar(4000));
        }
```

**Comment by MalcolmMcNeely** [comment]
When I profile this code, I see multiple SqlConnection objects in memort, presumably internally created:
![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/d8b8bc49-7be2-4f51-ba9f-4272abf1e832)

Of these objects, one of them is always pooled:
![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/ef37082f-8d23-4c12-a84d-8ec41104ec86)

When I look at the creation stack trace:
![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/4c6f731c-4501-47aa-a8fb-36c5774c1cf5)

`ConnectionHelprs.UpdateConnectionInfoIfCloud` is setting the connection to pooled:
![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/aaf516b8-cee5-497d-baac-df73c7ab65e9)

ServerConnection.cs:
![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/b18b59bf-2028-455a-8fd7-3abe3d49629c)

**Comment by MalcolmMcNeely** [comment]
Trying out both options I see the following results:

There is no longer a `SqlConnection` in memory when I profile the app, however the database still shows a connection which lasts until I kill the app:
![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/dc1edbda-8f12-41e1-9a8b-b4d583adeff8)

Our main use case is we want to use Azure Severless SQL databases, so if the connection remains open then the databases won't sleep after the auto-pause delay, which is costing us significantly.

**Comment by MalcolmMcNeely** [comment]
Not sure if this is relevant but I do see my connection into the `SqlConnectionFactory._connectionPoolsGroups` property when I profile:

![image](https://github.com/microsoft/sqlmanagementobjects/assets/41832976/887ee519-479b-4a2a-b2e3-f035dfe1840c)

Both `SqlConnectionFactory._poolsToRelease` and `SqlConnectionFactory._poolGroupsToRelease` are 0.

**Comment by shueybubbles** [comment]
thx for the update. There are a few steps to follow next; I will try to look at it today if you don't get ahead of me.
1. Make sure `ServerConnection.Disconnect` is calling `SqlConnection.Close`. It's possible that `ServerConnection` may decide not to call `Close` if you passed the `SqlConnection` to it in the constructor, with the theory that the caller "owns" the connection lifetime. If that is the case you can try calling `SqlConnection.Close` yourself instead of relying on `ServerConnection`.
2. If the connection is indeed being closed by your app but the server is still reporting it being around:
3. Remove SMO from the repro entirely and just open a SqlConnection, run a query, and close the connection and see if the connection still persists on the server until the app exits.
4. If that happens, turn on ETL traces for SqlClient and see if there's any clue as to why it's keeping the internal TDS connection alive.  You can record the events with code (eg https://github.com/microsoft/sqlmanagementobjects/blob/main/src/FunctionalTest/Framework/Helpers/SqlClientEventRecorder.cs) or using xperf `xperf -start trace -f myTrace.etl -on *Microsoft.Data.SqlClient.EventSource`
5. Depending on the results of steps 3 and 4, we may have to open an issue against SqlClient or dig deeper in the SMO code.

**Comment by shueybubbles** [comment]
One more thing - if Microsoft.Data.SqlClient keeps the connection open after Close but System.Data.SqlClient does not, that'll be a useful data point to share with the SqlClient folks

**Comment by shueybubbles** [comment]
I found the other source of the extra connection. `ServerConnection.GetDatabaseConnection` doesn't bother to see if it's already connected to the database; it could just return itself if so.
```C#
        public ServerConnection GetDatabaseConnection(string dbName, bool poolConnection = true)
        {
            return ConnectionFactory.GetInstance(this).GetDatabaseConnection(dbName, poolConnection, this.AccessToken);
        }
```
The workaround for this problem is to disconnect it manually when you are done with the `Database` object

```C#
database.ExecutionManager.ConnectionContext.Disconnect();
```

For some applications it's possible that this connection gets garbage collected in some reasonable time after the Database object goes out of scope.

I will verify that returning a reference to itself doesn't break other scenarios then try to get a fix out in the next few weeks.

**Comment by MalcolmMcNeely** [comment]
Great that fixed it. Confirmed that the severless database went to sleep while the app was active. Thanks for your help!

**Comment by jvmlet** [comment]
We also experiencing some weird  behavior with idle sessions, code snippet for `Server` and `Database` object registrations with  Autofac DI : 
```c#

        services.AddScoped<Server>(sp => {
            string connectionString = sp.GetService<IOptions<ConnectionStrings>>().Default;
 
            SqlConnection sqlConnection = new SqlConnection(appConnectionString);
            sp.GetAutofacRoot().Disposer.AddInstanceForDisposal(sqlConnection); // the Dispose() IS called when scope (web request) goes away
            return new Server(new ServerConnection(sqlConnection));
        });
        services.AddScoped<Database>(sp => {
            Server server = sp.GetRequiredService<Server>();
            string dbName = new SqlConnectionStringBuilder(server.ConnectionContext.ConnectionString)
                .InitialCatalog;
            return server.Databases[dbName];
        });
```

The connection is closed, but session remains idle and after some  we get `Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server tcp:our_synapse.azuresynapse.net,1433. ---> Microsoft.Data.SqlClient.SqlException (0x80131904): 111219;The maximum concurrent session limit of 512 exceeded.`

Please advise.

**Comment by shueybubbles** [comment]
@jvmlet Until we have a fix, my recommendation is the same - specifically call 
`database.ExecutionManager.ConnectionContext.Disconnect();`
after completing the tasks with a `Database` object

**Comment by shueybubbles** [comment]
Please try out SMO version 170.21 to see if the connection leak for your scenario has been fixed.

**Comment by MalcolmMcNeely** [comment]
Fix confirmed, many thanks for your help.
