### ISSUE TITLE
Dependency to SqlClient 2.0.0

### ISSUE THREAD

**Issue by t-mxcom** [microsoft/sqlmanagementobjects#16]
Hi everybody,

in version `161.40241.8-preview` of the SMO you announced to move to SqlClient 2.0.0.

I'm currently using version `160.2004021.0` of the `Microsoft.SqlServer.SqlManagementObjects` NuGet package in one of my applications, that also uses version `2.0.0` of the `Microsoft.Data.SqlClient` NuGet package.

As the new SqlClient contains changes according to securing the channel, I'm currently required to set `TrustServerCertificate` to `true` when creating the `Microsoft.SqlServer.Management.Common.ServerConnection`.
Unfortunately, when I'm using `Microsoft.SqlServer.Management.Smo.Transfer` to create a copy of a database, I cannot specify `TrustServerCertificate` for the connection to the destination database - at least, I couldn't find a way yet.

If there is already a way to do this, please give me a hint.
If there isn't, please consider adding this option to the `Transfer` class.

Thank you!

**Comment by shueybubbles** [comment]
Can you provide sample code showing how you create the `Transfer`?

**Comment by shueybubbles** [comment]
I think I see the part of the code that is omitting important pieces of the connection string. I don't think it supports azure active directory auth either, among other limitations. I would guess the workaround would be to not set a DestinationServer object and set Transfer.ScriptingOptions yourself to whatever version you need, but that doesn't help if you are using the TransferData method.

I think the right fix will be to expose a ServerConnection setter on Transfer instead of just the string parameters for the connection string.

**Comment by t-mxcom** [comment]
Good morning,
(it's about 9 am here in Austria)

I'm creating and using the `Transfer` object as follows:

```cs
string destinationDatabaseUser = "destination-db-user"; // may not be specified when using Windows Authentication in the company network
string destinationDatabasePassword = "destination-db-password"; // may not be specified when using Windows Authentication in the company network

// source database
ServerConnection sourceServerConnection = CreateSourceServerConnectionAndSetOptions();
Server sourceServer = new Server(sourceServerConnection);
DatabaseCollection sourceDatabaseCollection = sourceServer.Databases;
Database sourceDatabase = sourceDatabaseCollection[SourceDatabase];

// destination database
ServerConnection destinationServerConnection = CreateDestinationServerConnectionAndSetOptions();
Server destinationServer = new Server(destinationServerConnection);
DatabaseCollection destinationDatabaseCollection = destinationServer.Databases;
Database destinationDatabase = destinationDatabaseCollection[DestinationDatabase];

// setup transfer
Transfer transfer = new Transfer(sourceDatabase);
transfer.CopyAllDatabaseTriggers = false;
// set a lot of other options on Transfer
transfer.DestinationDatabase = destinationDatabase.Name;
transfer.DestinationServer = destinationServer.Name;
if ((string.IsNullOrEmpty(destinationDatabaseUser)) &&
	(string.IsNullOrEmpty(destinationDatabasePassword)))
{
	// use Windows Authentication
	transfer.DestinationLoginSecure = true;
}
else
{
	// use SQL Server authentication
	transfer.DestinationLogin = destinationDatabaseUser;
	transfer.DestinationPassword = destinationDatabasePassword;
}
transfer.CopySchema = true;
StringCollection transferScript = transfer.ScriptTransfer();
// log transfer script to file
transfer.TransferData();
```

As you wrote, adding all possible connection string options as single properties may be a solution, but adding another ServerConnection property which will be used by `TransferData` when connecting to the destination is the most flexible one!
Great idea!

**Comment by shueybubbles** [comment]
`Transfer` now has a `DestinationServerConnection` property to set
