### ISSUE TITLE
What TargetFrameworks should the SMO Nuget package support?

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/sqlmanagementobjects#17]
Today SMO supports net472 and netstandard2.0.
Netcoreapp3.1 expands the capabilities of NetCore, such as #6 . 
When we upgrade SMO to produce a netcoreapp3.1 build, will there still be any value in producing a netstandard2.0 target?
The build and test matrix gets complicated very quickly as we add new targets.

**Comment by shueybubbles** [comment]
will definitely add netcoreapp3.1 see #21

**Comment by dbaduck** [comment]
I would say that netstandard2.0 should not be a target being that PowerShell 7 is netcoreapp3.1 and PowerShell 5.1 is on the net472. I don't see these requirements to be too much and I don't think SMSS uses netstandard2.0. But I don't write a ton of C# implementations using SMO so netstandard2.0 may be on someone's radar. My $0.02.
