### ISSUE TITLE
Constructor on type 'Microsoft.SqlServer.Management.Smo.SqlObjectUnion' not found.'

### ISSUE THREAD

**Issue by jzabroski** [microsoft/sqlmanagementobjects#2]
@Tornhoof

Thanks for your help. This is the closest Microsoft-owned repo to record this issue against.  This is a pretty difficult bug, as I've tried to workaround it by using net48 and run into other issues in the process.

*Issue*
When using Microsoft.SqlServer.SqlManagementObjects nuget package, calling `EnumObjectPermissions` does not work because SqlObjectUnion class is missing a required constructor.

*Details*

I cannot actually use the netstandard2.0 binaries shipped as part of https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/150.18208.0 or the latest preview https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/160.1911221.0-preview

When I use the following snippet, it blows up:

```c#
using (var sqlConnection = new SqlConnection(GetConnectionString(applicationArguments)))
{
  var serverConnection = new ServerConnection(sqlConnection);
  var server = new Server(serverConnection);
  var database = server.Databases[applicationArguments.DatabaseName];

  var objectPermissionInfos = _database.EnumObjectPermissions();
```

**Comment by jzabroski** [comment]
@shueybubbles Missed this issue being closed during the COVID-19 hysteria - can I get an explanation on whether this is fixed in the new package https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/160.2004021.0

**Comment by shueybubbles** [comment]
yes it should be fixed in the newest package.
