### ISSUE TITLE
Add IsAcceleratedDatabaseRecoveryOn property in SMO.Database

### ISSUE THREAD

**Issue by dbaduck** [microsoft/sqlmanagementobjects#22]
I would like to request that a property is added, and a facility to change it with .Alter() added for Accelerated Database Recovery, which is a new feature in SQL 2019. Having to write a query to find those databases that do not have it enabled should not have to be done.  It is in the sys.databases view and is a database property.

Please add a property bool IsAcceleratedDatabaseRecoveryOn { get; set; } to give us parity with properties that are changeable for databases.

sys.databases.is_accelerated_database_recovery_on (true or false)

Thanks.

**Comment by shueybubbles** [comment]
I followed a pre-existing C# naming convention and added 3 properties:

```
AcceleratedRecoveryEnabled
PersistentVersionStoreFileGroup
PersistentVersionStoreSizeKB
```

The first property can be used for both Create and Alter. The second can be used for Create and Alter, but has no effect in Alter when setting AcceleratedRecoveryEnabled to false.
The third property is read only. 

Try it out from https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/161.41981.14-msdata

**Comment by dbaduck** [comment]
Thank you very much. This will really help out in the automations.
