### ISSUE TITLE
SMO causing failed logins only for DB info

### ISSUE THREAD

**Issue by wishbone25** [microsoft/sqlmanagementobjects#25]
I'm using SMO version 150.18208.0. I use impersonation/connect as to pull in instance information, databases and user info for my servers. 

I'm able to authenticate to each server fine using connect as and I'm able to pull in the data correctly. The issue I have is that when iterating the databases to gather information like status or last backup time, we see failed logins on our database server. The failed logins are coming from the accountname of who the program is running under and not from the connectAsUsername. The odd thing is that I do get the data that I need. It almost seems like SMO first tries to connect to each database using the local account first and then it fails and uses the connect. When pulling in database users we do not see any failed logins.

Code:

**// connection info**
 var SQL_Connection = new ServerConnection(instance_str_name);
SQL_Connection.LoginSecure = true;
SQL_Connection.ConnectAsUser = true;
SQL_Connection.ConnectAsUserName = auth_profile_username;
SQL_Connection.ConnectAsUserPassword = auth_profile_password;
SQL_Connection.ConnectTimeout = 20;

**// get instance level user stuff (code ommitted for simplicity). There are NO failed logins in this loop**
foreach (Microsoft.SqlServer.Management.Smo.Login sqlInstance_Login in sqlInstance.Logins)
{
     var sqlInstance_Login.IsPasswordExpired = sqlInstance_Login.IsPasswordExpired;
}

**// get database information. This is where we see failed logins from the account running the program. It's almost like it doesn't try the 'ConnectAsUserName' first and instead tries the local account running the program**
foreach (Microsoft.SqlServer.Management.Smo.Database DB in sqlInstance.Databases)
{
   var dbStatus = DB.Status; // Causes a failed login
   var DBName = DB.Name; // Does Not cause a failed login
   var DBCreationDate = DB.CreateDate; // Causes a failed login
   var LastBackupDate = DB.LastBackupDate; // Causes a failed login

 **Note: If I do a debug and look at the variables above, they do have the correct data in them. My theory Why we see a failed login is a mystery to me. If I simply comment out the fields above we do not see any failed logins (even with the code below still in place)** 

    **// No failed logins here. The data is retreived.**
     foreach (User uname in DB.Users)
     {
        string user_login_type = Conversions.ToString(SDHC.get_user_login_type_string((int)uname.LoginType));
        string user_type = Conversions.ToString(SDHC.get_user_type_string((int)uname.UserType));
     }

}

**Note: Here is the failed login message we see from the database side:**
Login failed for user '[accountNameRunningTheProgram]'. Reason: Could not find a login matching the name provided
Error 18456, Severity: 14, State: 5.

Because of security reasons we cannot add permissions for the local account that is running the program to all of our SQL servers.

I'm not sure if this will work in the latest SMO 160+ since there is an issue with the ConnectionInfoExtended not being integrated.

**Comment by shueybubbles** [comment]
is the server in question on premises or Azure SQL DB? SMO has a few places where it creates new connections and maybe they are not copying the impersonation parameters properly for those new connections.

**Comment by wishbone25** [comment]
These are all on-premise.

**Comment by shueybubbles** [comment]
oh duh azure doesn't do integrated auth. <need more coffee/>

**Comment by wishbone25** [comment]
if it helps at all in that for loop where we receive failed logins we see one failed login each time we request one of those fields. So for each database we receive a failed login when we retrieve Status and another failed login when we retrieve LastBackupTime and so on. 

In other words it's not like it gets an initial failure and the rest are ok after that. Each one throws generated a failed login.

It's late enough, go for some Mt Dew :)

**Comment by shueybubbles** [comment]
any chance you could catch one of the failed logins as a SqlException in the debugger and put the stack trace here?

**Comment by wishbone25** [comment]
I added the following, but it doesn't seem to be actually tripping an exception. Let me know if I'm not doing something correctly.

try
{
  DBStatus_Text = DB.Status; 
  // I did confirm this is causing a failed login. I put breakpoints directly before and after to verify it's doing the failed login on this step. When I look at it in debug with a breakpoint DB.Status does have a valid value (Status = Normal).
}
catch (SqlException sqlEX)
{
  Console.Write(sqlEX.Message.ToString()); // This isn't tripped.
}

**Comment by shueybubbles** [comment]
SMO would have eaten the original SqlException before returning to your code. you'd have to tell the debugger to break on the first chance exception.
Microsoft.Data.SqlClient.SqlException

**Comment by wishbone25** [comment]
-		$exception	{System.Data.SqlClient.SqlException (0x80131904): Login failed for user '[DOMAIN\\LocalUserRunningCode....not the connectAsUsername]'.
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
ClientConnectionId:57805fcd-486c-42aa-a563-009506e36858
Error Number:18456,State:1,Class:14}	System.Data.SqlClient.SqlException
		Class	14	byte
+		ClientConnectionId	{57805fcd-486c-42aa-a563-009506e36858}	System.Guid
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		ErrorCode	-2146232060	int
+		Errors	{System.Data.SqlClient.SqlErrorCollection}	System.Data.SqlClient.SqlErrorCollection
		HResult	-2146232060	int
		HelpLink	null	string
		IPForWatsonBuckets	0x572f0ccc	System.UIntPtr
+		InnerException	null	System.Exception
		IsTransient	false	bool
		LineNumber	65536	int
		Message	"Login failed for user 'DOMAIN\\LocalUserRunningCode....not the connectAsUsername'."	string
		Number	18456	int
		Procedure	""	string
		RemoteStackTrace	null	string
		Server	"[SERVER]"	string
		Source	".Net SqlClient Data Provider"	string
		StackTrace	null	string
		State	1	byte
		TargetSite	null	System.Reflection.MethodBase
		WatsonBuckets	null	object
		_HResult	-2146232060	int
		_className	null	string
+		_clientConnectionId	{57805fcd-486c-42aa-a563-009506e36858}	System.Guid
+		_data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		_doNotReconnect	false	bool
		_dynamicMethods	null	object
+		_errors	{System.Data.SqlClient.SqlErrorCollection}	System.Data.SqlClient.SqlErrorCollection
		_exceptionMethod	null	System.Reflection.MethodBase
		_exceptionMethodString	null	string
		_helpURL	null	string
+		_innerException	null	System.Exception
		_ipForWatsonBuckets	0x572f0ccc	System.UIntPtr
		_message	"Login failed for user 'DOMAIN\\LocalUserRunningCode....not the connectAsUsername'."	string
		_remoteStackIndex	0	int
		_remoteStackTraceString	null	string
+		_safeSerializationManager	{System.Runtime.Serialization.SafeSerializationManager}	System.Runtime.Serialization.SafeSerializationManager
		_source	null	string
+		_stackTrace	{sbyte[24]}	object {sbyte[]}
		_stackTraceString	null	string
		_watsonBuckets	null	object
		_xcode	-532462766	int
		_xptrs	0x00000000	System.IntPtr
+		Static members

**Comment by wishbone25** [comment]
This exception was originally thrown at this call stack:
    System.Data.SqlClient.SqlInternalConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, bool, bool)
    System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, out bool)
    System.Data.SqlClient.TdsParser.Run(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject)
    System.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(bool)
    System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(System.Data.SqlClient.ServerInfo, string, System.Security.SecureString, bool, System.Data.ProviderBase.TimeoutTimer, bool, bool, bool)
    System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(System.Data.SqlClient.ServerInfo, string, System.Security.SecureString, bool, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Data.ProviderBase.TimeoutTimer)

**Comment by wishbone25** [comment]
As I stepped through the error the following was also thrown at that same line of code.

This exception was originally thrown at this call stack:
    System.Data.SqlClient.SqlInternalConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, bool, bool)
    System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, out bool)
    System.Data.SqlClient.TdsParser.Run(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject)
    System.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(bool)
    System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(System.Data.SqlClient.ServerInfo, string, System.Security.SecureString, bool, System.Data.ProviderBase.TimeoutTimer, bool, bool, bool)
    System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(System.Data.SqlClient.ServerInfo, string, System.Security.SecureString, bool, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Data.ProviderBase.TimeoutTimer)
    System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(System.Data.ProviderBase.TimeoutTimer, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, string, System.Security.SecureString, bool)



This exception was originally thrown at this call stack:
    System.Data.SqlClient.SqlInternalConnectionTds.SqlInternalConnectionTds(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, object, string, System.Security.SecureString, bool, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, string, bool, System.Data.SqlClient.SqlAuthenticationProviderManager)



This exception was originally thrown at this call stack:
    System.Data.SqlClient.SqlInternalConnectionTds.SqlInternalConnectionTds(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, object, string, System.Security.SecureString, bool, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, string, bool, System.Data.SqlClient.SqlAuthenticationProviderManager)
    System.Data.SqlClient.SqlConnectionFactory.CreateConnection(System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, object, System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions)
    System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionPoolGroup, System.Data.Common.DbConnectionOptions)
    System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal, out System.Data.ProviderBase.DbConnectionInternal)
    System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions)



This exception was originally thrown at this call stack:
    System.Data.SqlClient.SqlInternalConnectionTds.SqlInternalConnectionTds(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, object, string, System.Security.SecureString, bool, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, string, bool, System.Data.SqlClient.SqlAuthenticationProviderManager)
    System.Data.SqlClient.SqlConnectionFactory.CreateConnection(System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, object, System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions)
    System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionPoolGroup, System.Data.Common.DbConnectionOptions)
    System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal, out System.Data.ProviderBase.DbConnectionInternal)
    System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions)
    System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions)
    System.Data.SqlClient.SqlConnection.TryOpenInner(System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>)
    System.Data.SqlClient.SqlConnection.TryOpen(System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal>)
    System.Data.SqlClient.SqlConnection.Open()
    Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(System.Security.Principal.WindowsIdentity)

**Comment by shueybubbles** [comment]
thx. the ConnectionManager.InternalConnect way at the bottom is where the interesting part actually starts. I'll see if I can repro it.

**Comment by shueybubbles** [comment]
btw if you know ahead of time which properties on Database you want to fetch in your loop, you can increase performance using either Server.SetDefaultInitFields or Server.Databases.ClearAndInitialize to tell it the properties to query. It will reduce greatly the number of total queries for on premises servers. For Azure connections it will still have to connect to databases individually to fetch properties.

**Comment by shueybubbles** [comment]
@wishbone25  try this workaround - set NonPooledConnection = true

```
   var serverConnection = new ServerConnection(serverInstance)
               {
                   ConnectAsUser = true,
                   ConnectAsUserName = userName,
                   ConnectAsUserPassword = password,
                   NonPooledConnection = true
               };
```

Otherwise it seems SMO tries to create new connections for each database and doesn't copy the impersonation parameters.

**Comment by wishbone25** [comment]
The NonPooledConnection = true did the trick. No failed logins. Also thanks for the performance tip.
