### ISSUE TITLE
Could not load file or assembly 'Microsoft.SqlServer.BatchParser

### ISSUE THREAD

**Issue by gerjandev** [microsoft/sqlmanagementobjects#4]
When I reference the NuGet package Microsoft.SqlServer.SqlManagementObjects I get the error:

```
Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=15.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
```

With latest version 150.18097.0-preview:
```
Microsoft.SqlServer.BatchParser, Version=15.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
```

With stable version 140.17283.0
```
Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
```

Do I really need to install all the feature packs of SQL Server? So in this case 2017 and 2019? I already have installed 2014 and 2016

**Comment by shueybubbles** [comment]
@admalledd the batch parser has been considered an implementation detail of SMO so we haven't tried to preserve the API as we moved away from the native DLL. I recommend you open a new issue and we can look into exposing something equivalent in the new DLL.

**Comment by shueybubbles** [comment]
> @bitbau FYI we have a preview version of SMO that removes the native code dependency altogether. Please try it out from https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/160.1911221.0-preview#
> 
> This update also helps fix our issue with 'Microsoft.SqlServer.BatchParser' loading.  Do you have an estimated date when this version will come out of preview?
When SSMS 18.5 releases later this year, the corresponding SMO version will be published as non-preview.

**Comment by lucasmatias** [comment]
> Mudei o alvo da plataforma para criar x64 dlls e agora funciona para mim. A instalação do Dotnet Framework 3.5 / 2.0 não funcionou tão bem quanto a instalação do vc ++ 2013 Runtime.
> ![2019-09-30 10_23_59-Clipboard](https://user-images.githubusercontent.com/39589216/65861523-b68a4980-e36c-11e9-94c2-12a01b956963.png)

Thank you very much, it worked here.

**Comment by lucasmatias** [comment]
> I switched the plattform target to build x64 dlls and now it works for me. Installing Dotnet Framework 3.5/2.0 didn't work as well as installing vc++ 2013 Runtime.
> ![2019-09-30 10_23_59-Clipboard](https://user-images.githubusercontent.com/39589216/65861523-b68a4980-e36c-11e9-94c2-12a01b956963.png)

Thank you very much, it worked here.

**Comment by medvevic** [comment]
> > @bitbau FYI we have a preview version of SMO that removes the native code dependency altogether. Please try it out from https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/160.1911221.0-preview#
> 
> The **preview version (160.1911221.0-preview)** is working for me. It fixed the error.

Thank you very much, it fix problem!

**Comment by DanielHolland** [comment]
> @bitbau FYI we have a preview version of SMO that removes the native code dependency altogether. Please try it out from https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/160.1911221.0-preview#

Can confirm this version fixed the the same error I was experiencing, thanks for the effort.
