### ISSUE TITLE
Core Microsoft.SqlServer.Smo calls ServiceBrokerEnum and causes a file not found error

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/sqlmanagementobjects#54]
Greetz!  We use the SMO DLLs from the `SqlServer` module in dbatools. I just noticed that we get an error in Linux each time we load the Core SMO DLL from https://www.powershellgallery.com/packages/SqlServer/21.1.18245

```
     | Could not load file or assembly 'Microsoft.SqlServer.ServiceBrokerEnum,
     | Version=15.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The
     | system cannot find the file specified.
```

I haven't noticed this before but I haven't looked at loading errors in years 😅 

/cc https://github.com/sqlcollaborative/dbatools/issues/7467

**Comment by shueybubbles** [comment]
is this error blocking something?

**Comment by shueybubbles** [comment]
@Matteo-T There's a netstandard2.0 version of servicebrokerenum in the SMO nuget package version 150.18218.0

Is that DLL included in the core PS module?

**Comment by Matteo-T** [comment]
Operator error! Duh! I'll add it right away and hopefully push it out with the upcoming version of the module (I'm having some odd build issues with nuget packages...)

**Comment by Matteo-T** [comment]
@potatoqualitee - Chrissy: if you drop me an e/mail (matteot@you.know.here.com) the odds of me not forgetting would grow exponentially :)

**Comment by potatoqualitee** [comment]
Thank you both so much 🙇🏼 !

**Comment by Matteo-T** [comment]
@potatoqualitee - the change is checked in. I'm waiting for one small change from some other Team and then push the new SQLServer module. I've added both the only two missing DLLs I saw which happened to be available: Microsoft.SqlServer.Dmf.dll and Microsoft.SqlServer.ServiceBrokerEnum.dll. I doubt you (or SMO) need the DMF one...

**Comment by potatoqualitee** [comment]
Fantastic! Thank you 😊

**Comment by potatoqualitee** [comment]
I ended up diving into 48 hours of SMO and now have the latest SMO and Microsoft.Data in our dev branch, thank you both 🥳

**Comment by Matteo-T** [comment]
@potatoqualitee - FWIW the new module I just released has the v150 version of the missing DLLs.
