### ISSUE TITLE
AD Impersonation with ConnectAsUser doesn't work on .NetCore

### ISSUE THREAD

**Issue by mikeTWC1984** [microsoft/sqlmanagementobjects#6]
I'm trying to connect to sqlserver with AD credentials (service account) using SMO. It works on .net framework but fails on .net core (on Windows).  It keep using my current user name, not the one I specify

``` Login failed for user 'myDomain\MyUser' ```
below is the sample code to reproduce:
```csharp
using System;
using Microsoft.SqlServer.Management.Common;

namespace smo
{
    class Program
    {
        static void Main(string[] args)
        {
            var smo = new ServerConnection("myServer");

            smo.ConnectAsUser = true;
            smo.ConnectAsUserName = "someUser";
            smo.ConnectAsUserPassword = "somePwd";
            smo.Connect();

            var msg = smo.ExecuteScalar("select @@version");
            Console.WriteLine(msg);
        }
    }
}
```

**Comment by shueybubbles** [comment]
ConnectAsUser is implemented using the WindowsIdentity class, which wasn't available in NetStandard the last I looked.

**Comment by mikeTWC1984** [comment]
@shueybubbles  Thanks for info. I see that class exist in .net core 3+, probably it would make sense to include version for .net core too. AD auth is still used and it's a huge PITA for switching to core, especially for linux.

**Comment by aaomidi** [comment]
I think it's just not supported in .NET Core last time i checked.

**Comment by shueybubbles** [comment]
msdn says netcore 3.1 has it. We've yet to build a fully netcore version of SMO, it's on my wish list for this year to do it.

**Comment by shueybubbles** [comment]
@mikeTWC1984  please try package version 161.42121.15-msdata
thx
