### ISSUE TITLE
Bug: Extended Events' `CreateSessionFromTemplate()` creates file paths with `\` on Linux

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/sqlmanagementobjects#60]
When using a template such as: https://github.com/sqlcollaborative/dbatools/blob/development/bin/XEtemplates/15%20Second%20IO%20Error.xml

The following file:
```
<target package="package0" name="event_file">
         <parameter name="filename" value="15_second_io_error" />
      </target>
```

Ends up as:

```
TargetFile   : {/var/opt/mssql/log\15_second_io_error}
```

When using

```
$session = $store.CreateSessionFromTemplate($Name, $file)
$session.Create()
```

It still works, but would be cleaner to be `/var/opt/mssql/log/15_second_io_error`

**Comment by shueybubbles** [comment]
AFAICT SMO passes the filename "as is" to the server, without prepending the log folder path. 
Is the file on the server actually created with `\` or is the client showing the wrong value? 
Can you look at the actual tsql session.Creates sends to the server ? If it's just passing the plain file name and the server creates the file using `\` then this would seem like a server bug not a SMO bug.

**Comment by potatoqualitee** [comment]
Yep, you're right! `ADD TARGET package0.event_file(SET filename=N'15_second_io_error') WITH (MAX_MEMORY=4096 KB...`

Would you happen to know where can I log a SQL on Linux bug nowadays? 

Thank you 🙇🏼

**Comment by shueybubbles** [comment]
aka.ms/sqlfeedback is monitored. I will let the xevent owners know too.

**Comment by shueybubbles** [comment]
@potatoqualitee  what component is showing the TargetFile path with the \? 
On my linux container the actual xel file looks like it's in the right place. I created it with the file name `slash`

```
root@sqltoolststagtlinux:/home/SqlTools# docker exec keep_sql2019Linux ls /var/opt/mssql/log
HkEngineEventFile_0_132659915860370000.xel
errorlog
errorlog.1
log_1508.trc
log_1509.trc
log_1510.trc
log_1511.trc
log_1512.trc
slash_0_132711818807260000.xel
```

**Comment by potatoqualitee** [comment]
Thank you for the link! Totally embarrassed, the bad parsing was on my end.
