### ISSUE TITLE
Package dependency loop - please fix it

### ISSUE THREAD

**Issue by Matteo-T** [microsoft/sqlmanagementobjects#61]
When I try to install the package via PowerShell (v7), I get an error about a dependency loop.

Repro:

```powershell
Install-Package -Name Microsoft.SqlServer.SqlManagementObjects -ProviderName NuGet -Scope CurrentUser  -Force -Destination $env:TEMP\SMO
```

Result:
```
Install-Package: Dependency loop detected for package 'Microsoft.SqlServer.SqlManagementObjects'.
```

**Comment by Matteo-T** [comment]
@shueybubbles - I thought we fixed this a while back, but I guess I was wrong. IIRC,

Perhaps, we should have the Microsoft.SqlServer.Assessment folks look into it, since I see it here - the loop may be coming from the dependency on Microsoft.SqlServer.Assessment (or maybe others?):

```powershell
Install-Package -Name Microsoft.SqlServer.Assessment  -ProviderName NuGet -Scope CurrentUser  -Force -Destination $env:TEMP\Asmt
```

Result:
```
Install-Package: Dependency loop detected for package 'Microsoft.SqlServer.Assessment'.
```

**Comment by shueybubbles** [comment]
It's a bug in the PS package manager not in the packages

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Matteo-T** [comment]
Oh cool...  is it known? I could not find a bug, but I did see a bunch of posts. And a promise from the PS guys to fix it. I'll see if I can find the bug and put it here, in case others run into it.

**Comment by tcartwright** [comment]
I wrote an XmlTreePackage script as I was trying to figure out what the loop on this very package was. I don't know if it will help you guys debug this, but here it is: [XmlTreePackage.ps1](https://gist.github.com/tcartwright/ec8b5103e1b7d6924571aa5b798e2f02)

**Comment by tcartwright** [comment]
I wrote this to work around the dependency loop. Takes it a while, but it downloads all 177 dependencies! WOW:

https://gist.github.com/tcartwright/69613fb4766eda2615cb1670f0ca154a

**Comment by potatoqualitee** [comment]
@tcartwright - I asked in another thread and we actually only need two

> I think you can work around this by using -SkipDependencies parameter. You'd just need to also install Microsoft.Data.SqlClient and Microsoft.Data.SqlClient.SNI

I was able to use this with success.

**Comment by tcartwright** [comment]
@potatoqualitee TYVM Chrissy. Now the only issue I have with what you are saying is that works for now. What about the next redesign when the package architecture changes again? I would prefer my scripts to be stable regardless. :(

**Comment by potatoqualitee** [comment]
I agree entirely! I think this is a PowerShell team issue, however. I cannot get any Package to install, SQL related or not 💔

**Comment by tcartwright** [comment]
@potatoqualitee Chrissy, the download package ps1 I wrote a couple days ago will download any package for you and all of its dependencies. Regardless of loops.  You might want to try it out. I tried to ensure it only downloaded each package once.

**Comment by shueybubbles** [comment]
This is not a SMO issue.
