### ISSUE TITLE
Can't use `SmoDependencyDiscoverer` - NullReferenceException

### ISSUE THREAD

**Issue by Herve-M** [microsoft/sqlmanagementobjects#70]
Hello,

I found a little bug when using  `SmoDependencyDiscoverer`: one of the internal prop. isn't instantiated ending into a `System.NullReferenceException: 'Object reference not set to an instance of an object.'`

Prop. in question: (internal) `CreatingObjectDictionary creatingDictionary`

Example code: 
```
_smoDependencyDiscoverer = new SmoDependencyDiscoverer(_server);
 _smoDependencyDiscoverer.Discover(smoToCheck)
```

Waited behavior: 
Can use `SmoDependencyDiscoverer` with provided ctor.

Current behavior: 
Can't use `SmoDependencyDiscoverer` with provided ctor and/or prop. settings.

Information:
- Entry assembly target: netstandard2.1
- Version: Microsoft.SqlServer.Smo, Version=16.200.0.0 (NuGet: 161.46437.65 )

Don't hesitate for any question,
Herve-M

**Comment by shueybubbles** [comment]
thx for the report. This class is really intended to be used by `ScriptMaker` , not by itself. The only reason the class is public is so Sql Server Management Studio can use it. It uses it thusly:

```C#

private static ScriptMaker GetScriptMaker(Smo.Server server, ScriptingOptions options, ScriptBehavior behavior)
{
    ScriptMaker scriptMaker = GetScriptMaker(server, options);
    scriptMaker.Preferences.Behavior = behavior;
    scriptMaker.Discoverer = GetDiscoverer(server, options, behavior);
    return scriptMaker;
}

private static ScriptMaker GetScriptMaker(Smo.Server server, ScriptingOptions options)
{
    return new ScriptMaker(server, options);
}

private static ISmoDependencyDiscoverer GetDiscoverer(Smo.Server server, ScriptingOptions so, ScriptBehavior behavior)
{
    SmoDependencyDiscoverer dependencyDiscoverer = new SmoDependencyDiscoverer(server, so);
    dependencyDiscoverer.Preferences.Behavior = behavior;
    return dependencyDiscoverer;
}

```

**Comment by Herve-M** [comment]
Interesting! 
Now that I learned about `ScriptMaker`, does it replace  `Scripter` who work with/on `DependencyWalker`?

**Comment by shueybubbles** [comment]
`Scripter` uses `ScriptMaker` in its implementation, and `SmoDependencyDiscoverer` uses `DependencyWalker` in its implementation.
The main benefit of using `ScriptMaker` would be the ability to pass in your own implementation of `ISmoScriptWriter`. That's how SSMS is able to write scripts directly to different types of files or the clipboard etc in the Generate Scripts wizard.

**Comment by Herve-M** [comment]
Ok, thanks for all the details :-)
