### ISSUE TITLE
Unit tests for created SMO objects

### ISSUE THREAD

**Issue by vizo92** [microsoft/sqlmanagementobjects#73]
I am writing an application using SMO for creating tables definied by user. Users will be able to use them later.
I was trying to write Unit Tests using xUnit and Moq but i can't mock server/database/table (parent objects) because they're sealed classes and don't have single interface describing all options they have. I would like to test things before creating them in database.

Can you explain me how to write unit tests for created objects, for example Columns?

C#

**Comment by shueybubbles** [comment]
`Database` class has a "design mode" concept that allows you to instantiate a Database and add tables etc to it without persisting it to a real server.  It's not well tested and not really supported, though we have a unit test internally that shows how to turn on design mode. The trick is to set the Server object to `Offline` mode.  With a database in design mode you have to manually populate all the collections and properties of the objects with your code. Trying to read a property value on an object will not send a query to the server, so if you haven't set a property and try to read it the app will throw an exception.
It may be worth trying out for your unit test purposes.

```C#

        [TestCategory("Unit")]
        [TestMethod]
        public void Database_default_constructor_sets_designmode()
        {
            // setting ServerVersion allows setting Database.Parent without a server query to get the version
            var serverConnection = new ServerConnection() { ServerVersion = new ServerVersion(15, 0), TrueName = "designMode" };
            var server = new Management.Smo.Server(serverConnection);
            // designmode requires an offline connection
            (server as ISfcHasConnection).ConnectionContext.Mode = SfcConnectionContextMode.Offline;
            var database = new Database()
            {
                Parent = server,
                Name = "dbname"
            };
            Assert.That(database.IsDesignMode, Is.True, "IsDesignMode");
            var script = database.Script();
            Assert.That(script.Cast<string>(), Is.EqualTo(new[] { "CREATE DATABASE [dbname]" }), "database.Script() in design mode");
        }

```

**Comment by vizo92** [comment]
Thanks for response, i'll check that. 

Anyone knows when SMO will became open source?

**Comment by shueybubbles** [comment]
@vizo92  now :-)
https://github.com/microsoft/sqlmanagementobjects/blob/98093604e9ede97aa2a9b066279f0bd9d9557c4f/src/UnitTest/Smo/DatabaseTests.cs#L110

**Comment by shueybubbles** [comment]
if designmode falls short of the goal, open issues here and perhaps it can be improved.
