### ISSUE TITLE
Timeout in Transfer.TransferData.ExecuteStatements()-Methods

### ISSUE THREAD

**Issue by forGG** [microsoft/sqlmanagementobjects#78]
Hello, I use the "Transfer" object to copy large databases. If I set CopySchema- and CopyData-Property to true, the flow of the "TransferData" method is roughly as follows:
1.	Create schema of tables with primary key
2.	Copy data
3.	Create Defaults and Indexes (...)

My problem now is that after copying the data, the indexes are created. The ExecuteStatements() method is used to create these (Epilogue). A command timeout of 120 is set in this. This causes an exception to be thrown for large tables (> 10,000,000 data records). The 120 seconds are not enough to create the key of the table. It would be desirable here that the StatementTimeout property of the DestinationServerConnection would be used.

Kind regards

**Comment by shueybubbles** [comment]
good catch. I'll change it to this. For a long time SMO was creating the destination connection itself so it always had the default 30 second value in destinationConnection.

`CommandTimeout = Math.Min(120, destinationConnection.CommandTimeout)`

**Comment by forGG** [comment]
Great, when is the next release planned?

**Comment by shueybubbles** [comment]
Try 161.47008.0

**Comment by forGG** [comment]
Hi,

I looked at the changes and saw that the CommandTimeout is being used by the SqlConnection of the ServerConnection object. Is it correct that this CommandTimeout can only be set via a ConnectString? I couldn't find a corresponding property in the ServerConnection object.

I've solved it this way, but I find it a bit cumbersome.

        static ServerConnection GetDestinationServerConnection(Options options)
        {
            SqlConnectionStringBuilder sqlConnectionStringBuilder = new SqlConnectionStringBuilder
            {
                DataSource = options.DestinationServer,
                InitialCatalog = options.DestinationDatabase,
                CommandTimeout = 0,
                IntegratedSecurity = options.LoginSecure.GetValueOrDefault()
            };
            if (!sqlConnectionStringBuilder.IntegratedSecurity)
            {
                sqlConnectionStringBuilder.UserID = options.Login;
                sqlConnectionStringBuilder.Password = options.Password;
            }
            SqlConnection sqlConnection = new SqlConnection(sqlConnectionStringBuilder.ConnectionString);
            ServerConnection serverConnection = new ServerConnection(sqlConnection);
            return serverConnection;
        }

**Comment by shueybubbles** [comment]
One problem we have is SMO has to dual-build for `System.Data.SqlClient` and `Microsoft.Data.SqlClient` and the S.D.S version of `SqlConnection` doesn't have a `CommandTimeout` property. It's a gap in the code that `ServerConnection` doesn't conditionally set this property on connections it creates itself. I will try to fix that in a future release.
