### ISSUE TITLE
Open Source SMO

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/sqlmanagementobjects#80]
### Discussed in https://github.com/microsoft/sqlmanagementobjects/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **jzabroski** January  3, 2021</sup>
Hi,

I would be interested in fixing some bugs if SMO were to become open source, as well as make some API improvements to take advantage of C# 9 pattern matching.

Is this possible now?  </div>

**Comment by jzabroski** [comment]
Awesome.  And it's not 4/1.
