### ISSUE TITLE
SetDefaultInitFields() should be smarter and ignore unsupported fields/properties

### ISSUE THREAD

**Issue by matteot31415** [microsoft/sqlmanagementobjects#84]
Consider the following example:

  ```csharp
  // ... some code omitted ...
  var server = new Server("myserver");
  server.SetDefaultInitFields(typeof(AvailabilityGroup), server.DatabaseEngineEdition, "ClusterType", "IsManagedInstanceLink");

  // AG1 is an existing Availability Group
  var ag = server.AvailabilityGroups["AG1"];    // !! runtime exception here!! 
  ```

If the caller is not aware that "ClusterType" is only supported on SQL2017+, a runtime exception would be thrown when the AvailabilityGroup objet is populated (i.e. when its properties are fetched), because SMO/SFC blindly tried to get the unsupported properly.

This would force the user to implement custom (and cumbersome) logic to conditionally exclude the unsupported properties, which ultimately is what SMO should be taking care of. 

While it is understandable that `if you want to pre-fetch an property, it probably means you need it and you are using it- hence, it is implied that you are already prepared to handle the fact that is supported or not` may be reasonable, however it is possible that that logic is short-circuited or hidden several layers underneath.

So, in the principle of `being liberal in what you accept, and strict in what you produce`, I'm proposing to have an implementation of SetDefaultInitFields() that would just ignore the unsupported properties/fields, in other words I could happily write something like:

  ```csharp
  // ... some code omitted ...
  var server = new Server("myserver");
  server.SetDefaultInitFields(typeof(AvailabilityGroup), server.DatabaseEngineEdition, "Foo", "Bar");
  var ag = server.AvailabilityGroups["AG1"];  // No runtime exception, even though neither 'Foo' nor 'Bar' are supported
  ```
For the record, this issue is what caused SSMS 18.11 to [regress the HADR dashboard functionality]( https://feedback.azure.com/d365community/idea/ee71fb15-4999-ec11-a81c-000d3adfb8f5).

**Comment by Matteo-T** [comment]
Apparently, I had an identify crisis and logger this issue with my alter-account... :)

**Comment by shueybubbles** [comment]
@Charles-Gagnon   Something else to consider - add `Server.IsSupportedProperty<T>() where T:SqlSmoObject` so we can lookup property support without needing an instance of the SqlSmoObject. It would use the metadata provider the same way a smarter SetDefaultInitFields would.
