### ISSUE TITLE
Possibility of a Release with updated Microsoft.Data.SqlClient dependency?

### ISSUE THREAD

**Issue by SeanKilleen** [microsoft/sqlmanagementobjects#94]
Hi all,

I have some colleagues who are running into this issue: https://github.com/dotnet/SqlClient/issues/1390

They are using SMO within the space of a console application that happens to be running within a Linux container.

My understanding is that this is fixed in a later version of Microsoft.Data.SqlClient that is available (I'm working to confirm).

This doesn't seem like something that I'd be able to submit in terms of a PR, so out of curiosity -- how likely would the SMO team be to make a release with an updated dependency? (No wrong answers, just not sure how the release cycle works in this case.)

Thanks for any information you can provide!

**Comment by ErikEJ** [comment]
You should be able to just use a newer version by adding that as a package reference.

**Comment by SeanKilleen** [comment]
@ErikEJ great point; I'll ensure that they've tried adding the newer version of Microsoft.Data.SqlClient as a direct dependency.

**Comment by shueybubbles** [comment]
Be careful about upgrading from M.D.S 3 to 4+. It defaults to "encrypt=true" if your connection string doesn't specify it.

**Comment by SeanKilleen** [comment]
Just wanted to say thank you for this response! The solution to explicitly take a dependency on Microsoft.Data.SqlClient did indeed resolve the issue in this case.

**Comment by duyn9uyen** [comment]
I've been struggling trying to upgrade our .NET 5 API to .NET 6 with for days! We host our API on a Linux containers in Kubernetes. The container kept crashing and I saw that it threw a `Segmentation fault (core dumped).` error. @SeanKilleen, saw you and knew I was close. Explicitly referencing Microsoft.Data.SqlClient 4.1.0 worked for me!

**Comment by SeanKilleen** [comment]
@duyn9uyen well, fancy seeing you here! 😆 Glad I was able to help you find a solution!
