### ISSUE TITLE
Please stop including SET QUOTED_IDENTIFIER OFF for external tables

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/sqlmanagementobjects#96]
Please quit including `SET QUOTED_IDENTIFIER OFF` when scripting out the `CREATE` of an external table?

This causes an error in Synapse:
`Msg 104409, Level 16, State 1, Line 9
Setting QUOTED_IDENTIFIER to 'OFF' is not supported.`

**Comment by jzabroski** [comment]
@SQLvariant you can add a regression test by following some of the examples:

**Comment by shueybubbles** [comment]
For this case I think it makes sense to hard code the `QuotedIdentifierStatus` property to 1 for DW

eg

```xml
<version datawarehouse_enabled='true'>
<property name="QuotedIdentifierStatus" type="bit" cast='true' read_only_after_creation="true" mode="design">1</property>
</Version>
```

Today it's using an `OBJECTPROPERTY` for all versions:

```xml
<property name="QuotedIdentifierStatus" type="bit" cast='true' read_only_after_creation="true" mode="design">ISNULL(OBJECTPROPERTY(tbl.object_id,N'IsQuotedIdentOn'),0)</property>
```

**Comment by shueybubbles** [comment]
Well, this clarifies things a bit, from the docs:

```
When a table is created, the QUOTED IDENTIFIER option is always stored as ON in the table's metadata even if the option is set to OFF when the table is created.
```
So we can just change the default from `0` to `1` for tables when the objectproperty is null.
